services:
  db:
    image: postgres:17-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - nutrifit-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  nutrifit-data:
